replicaCount: 3
image:
  repository: acrexercise.azurecr.io/nginxnew
  tag: v1
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

container:
  port: 8080

probes:
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10
    path: /
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 15
    path: /